# Generated by Django 2.2.6 on 2019-11-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Status do reserva',
                'verbose_name_plural': 'Status dos reservas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('hora_checkin', models.TimeField(blank=True, null=True)),
                ('hora_checkout', models.TimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.Cliente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quartos.Quarto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.StatusReserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
