# Generated by Django 2.2.6 on 2019-11-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_registro',
        ),
    ]
