# Generated by Django 2.2.6 on 2019-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='produtos/')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
            },
        ),
    ]
