# Generated by Django 2.2.6 on 2019-11-04 01:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusQuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Status do quarto',
                'verbose_name_plural': 'Status dos quartos',
            },
        ),
        migrations.CreateModel(
            name='TipoCama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo da cama',
                'verbose_name_plural': 'Tipos da cama',
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número do quarto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quartos.StatusQuarto', verbose_name='Situação do quarto')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
            },
        ),
        migrations.CreateModel(
            name='CamaQuarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quartos.Quarto')),
                ('tipo_cama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quartos.TipoCama', verbose_name='Tipo da cama')),
            ],
            options={
                'verbose_name': 'Camas do quarto',
                'verbose_name_plural': 'Camas dos quartos',
            },
        ),
    ]
